/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const MenuItemId = IDL.Nat;
export const MenuCategory = IDL.Variant({
  'Burger' : IDL.Null,
  'Pizza' : IDL.Null,
  'Sandwiches' : IDL.Null,
  'Beverages' : IDL.Null,
  'Maggi' : IDL.Null,
  'Momos' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : MenuCategory,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Ready' : IDL.Null,
  'Baking' : IDL.Null,
  'Preparing' : IDL.Null,
  'OutForDelivery' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const OrderItem = IDL.Record({
  'itemId' : MenuItemId,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const OrderPublic = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'customerPhone' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'timestamp' : Timestamp,
  'items' : IDL.Vec(OrderItem),
  'orderNumber' : IDL.Text,
});
export const PlaceOrderRequest = IDL.Record({
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'customerPhone' : IDL.Text,
  'items' : IDL.Vec(IDL.Tuple(MenuItemId, IDL.Nat)),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [MenuCategory],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
  'getOrderStatus' : IDL.Func([OrderId], [IDL.Opt(OrderStatus)], ['query']),
  'getOrdersByStatus' : IDL.Func(
      [OrderStatus],
      [IDL.Vec(OrderPublic)],
      ['query'],
    ),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [OrderPublic], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const MenuItemId = IDL.Nat;
  const MenuCategory = IDL.Variant({
    'Burger' : IDL.Null,
    'Pizza' : IDL.Null,
    'Sandwiches' : IDL.Null,
    'Beverages' : IDL.Null,
    'Maggi' : IDL.Null,
    'Momos' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : MenuCategory,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Ready' : IDL.Null,
    'Baking' : IDL.Null,
    'Preparing' : IDL.Null,
    'OutForDelivery' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const OrderItem = IDL.Record({
    'itemId' : MenuItemId,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const OrderPublic = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'customerPhone' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'timestamp' : Timestamp,
    'items' : IDL.Vec(OrderItem),
    'orderNumber' : IDL.Text,
  });
  const PlaceOrderRequest = IDL.Record({
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'customerPhone' : IDL.Text,
    'items' : IDL.Vec(IDL.Tuple(MenuItemId, IDL.Nat)),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [MenuCategory],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(OrderPublic)], ['query']),
    'getOrderStatus' : IDL.Func([OrderId], [IDL.Opt(OrderStatus)], ['query']),
    'getOrdersByStatus' : IDL.Func(
        [OrderStatus],
        [IDL.Vec(OrderPublic)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [OrderPublic], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };