/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type MenuCategory = { 'Burger' : null } |
  { 'Pizza' : null } |
  { 'Sandwiches' : null } |
  { 'Beverages' : null } |
  { 'Maggi' : null } |
  { 'Momos' : null };
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : MenuCategory,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type MenuItemId = bigint;
export type OrderId = bigint;
export interface OrderItem {
  'itemId' : MenuItemId,
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface OrderPublic {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'paymentMethod' : string,
  'customerPhone' : string,
  'totalAmount' : bigint,
  'timestamp' : Timestamp,
  'items' : Array<OrderItem>,
  'orderNumber' : string,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Ready' : null } |
  { 'Baking' : null } |
  { 'Preparing' : null } |
  { 'OutForDelivery' : null };
export interface PlaceOrderRequest {
  'customerName' : string,
  'deliveryAddress' : string,
  'paymentMethod' : string,
  'customerPhone' : string,
  'items' : Array<[MenuItemId, bigint]>,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[MenuCategory], Array<MenuItem>>,
  'getOrder' : ActorMethod<[OrderId], [] | [OrderPublic]>,
  'getOrderStatus' : ActorMethod<[OrderId], [] | [OrderStatus]>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<OrderPublic>>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], OrderPublic>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];